name: inception
services:
#---------------------------------------
  nginx:
    container_name:   nginx
    build:            requirements/nginx
    restart:          on-failure
    env_file: .env
    depends_on:
                    - wordpress
    ports:
      - 80:80
      - 443:443

    volumes:
      - wordpress-volume:/www
    networks:
      - wp-nginx_network
#---------------------------------------
  wordpress:
    container_name:   wordpress
    build:            requirements/wordpress
    restart:          on-failure
    env_file: .env
    depends_on:
                    - mariadb

    volumes:
      - wordpress-volume:/www
    networks:
      - wp-nginx_network
      - db_network
    secrets:
      - db_user
      - db_password
      - db_name
      - wp_admin_password
      - wp_admin_name
      - wp_admin_email
      - wp_user_password
      - wp_user_name
      - wp_user_email
#---------------------------------------
  mariadb:
    container_name:   mariadb
    build:            requirements/mariadb
    restart:          on-failure
    env_file: .env

    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - db_network
    secrets:
      - db_user
      - db_password
      - db_name
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
volumes:
  wordpress-volume:
    driver_opts:
      type: none
      o:    bind
      device: /home/${USER}/data/wordpress-volume
  db-volume:
    driver_opts:
      type: none
      o:    bind
      device: /home/${USER}/data/db-volume

networks:
  wp-nginx_network:
  db_network:

secrets:
  db_user:
    file: ../secrets/db_user.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_name:
    file: ../secrets/db_name.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_admin_name:
    file: ../secrets/wp_admin_name.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_user_name:
    file: ../secrets/wp_user_name.txt
  wp_user_email:
    file: ../secrets/wp_user_email.txt
