name: inception
services:
  nginx:
    container_name:   nginx
    build:            requirements/nginx
    ports:
      - 80:80
      - 443:443
    restart:          always

    volumes:
      - wordpress-volume:/www
    networks:
      - wp-nginx_network

  wordpress:
    container_name:   wordpress
    build:            requirements/wordpress
    restart:          always

    volumes:
      - wordpress-volume:/www
    networks:
      - wp-nginx_network
      - db_network

  mariadb:
    container_name:   mariadb
    build:            requirements/mariadb
    restart:          always

    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - db_network

volumes:
  wordpress-volume:
    driver_opts:
      type: none
      o:    bind
      device: /home/${USER}/data/wordpress-volume
  db-volume:
    driver_opts:
      type: none
      o:    bind
      device: /home/${USER}/data/db-volume
networks:
  wp-nginx_network:
  db_network:
