name: inception
services:
  nginx:
    container_name:   nginx
    build:            requirements/nginx

    ports:
      - 80:80
      - 443:443

    restart:          always
    volumes:
      - wordpress-volume:/www
    networks:
      - container_network

  wordpress:
    container_name:   wordpress
    build:            requirements/wordpress
    restart:          always
    volumes:
      - wordpress-volume:/www
    networks:
      - container_network

volumes:
  wordpress-volume:
  mariadb-volume:
networks:
  container_network:
